# Generated by Django 5.2.5 on 2025-09-05 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="summary",
            field=models.TextField(default="Error loading the summary."),
        ),
    ]
