# Generated by Django 5.2.5 on 2025-09-05 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0002_product_summary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="starRating",
            field=models.FloatField(default=0.0),
        ),
    ]
