# Generated by Django 5.2.5 on 2025-09-08 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0003_alter_product_starrating"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.CharField(default="N/A"),
        ),
    ]
