# Generated by Django 5.2.5 on 2025-09-08 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0004_product_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(default=None),
        ),
    ]
